GET http://localhost:3000/api/peliculas

###

GET http://localhost:3000/api/peliculas?s=Dun

###

GET http://localhost:3000/api/peliculas/8

###

POST http://localhost:3000/api/peliculas
Content-Type: application/json

{
    "titulo": "Project almanac",
    "sinopsis": "Adolescentes construyen una máquina del tiempo, pero su alegría se esfuma cuando descubren las repercusiones de sus acciones.",
    "anio": 2015
}

###

POST http://localhost:3000/api/peliculas
Content-Type: application/json

{
    "titulo": "Así en la Tierra como en el Infierno",
    "sinopsis": "Kilómetros y kilómetros de tortuosas catacumbas yacen bajo las calles de París, plagadas de incontables almas. Cuando un equipo de exploradores se aventura en este desconocido laberinto, se descubre cuál fue la verdadera función de esta ciudad.",
    "anio": 2014,
    "poster": "N/A"
}

###

PUT http://localhost:3000/api/peliculas/19
Content-Type: application/json

{
    "peliculaid": 19,
    "titulo": "Paw Patrol: La Súper Película",
    "sinopsis": "Un meteorito mágico aterriza en Adventure City y otorga superpoderes a los cachorros de PAW Patrol, convirtiéndolos en The Mighty Pups.",
    "anio": 2024,
    "poster": "https://m.media-amazon.com/images/M/MV5BMGI4NTNlODItMGJlZi00OTIwLTlkM2ItMWFkZjJhZDIzMDc3XkEyXkFqcGdeQXVyMTEyNzQ1MTk0._V1_SX300.jpg"
}

###

POST http://localhost:3000/api/peliculas/19/categoria
Content-Type: application/json

{
    "categoriaid": "2"
}

###

DELETE http://localhost:3000/api/peliculas/19/categoria
Content-Type: application/json

{
    "categoriaid": "1"
}

###

DELETE http://localhost:3000/api/peliculas/19